#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kernel-config-checker
Version  : 1
Release  : 1
URL      : https://github.com/clearlinux/kernel-config-checker/archive/1.tar.gz
Source0  : https://github.com/clearlinux/kernel-config-checker/archive/1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: kernel-config-checker-bin
Requires: kernel-config-checker-python3
Requires: kernel-config-checker-python
BuildRequires : buildreq-distutils3

%description
Kernel Config Checker (kcc)
===========================
.. contents:: **Table of Contents**
:backlinks: none

%package bin
Summary: bin components for the kernel-config-checker package.
Group: Binaries

%description bin
bin components for the kernel-config-checker package.


%package python
Summary: python components for the kernel-config-checker package.
Group: Default
Requires: kernel-config-checker-python3

%description python
python components for the kernel-config-checker package.


%package python3
Summary: python3 components for the kernel-config-checker package.
Group: Default
Requires: python3-core

%description python3
python3 components for the kernel-config-checker package.


%prep
%setup -q -n kernel-config-checker-1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533318122
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kcc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
